apiVersion: v1
kind: Service
metadata:
  name: cheaperservice
spec:
  selector:
    app: cheaperlabel
  type: LoadBalancer
  ports:
    - name: cheaperbackendport
      port: 8080
      targetPort: 8080
    - name: cheaperfrontendpot
      port: 3000
      targetPort: 3000
  externalIPs:
    - 192.168.99.100
